export default Object.freeze({
  MAIN_LAYOUT: "MainLayout",
  HOME: "Home",
  SEARCH: "Search",
  CART: "Cart",
  FAVOURITE: "Favourite",
  FORGOT_PASSWROD: "ForgotPassword",
  LOGIN: "Login",
  NOTIFICATION: "Notification",
  MY_WALLET: "MyWalet",
  ON_BOADING: "OnBoaring",
  OTP: "Otp",
  REGISTER: "Register",
  SETTINGS: "Settings",
});
