export default Object.freeze({
  MAIN_LAYOUT: "MainLayout",
  HOME: "Home",
  SEARCH: "Search",
  CART: "Cart",
  FAVOURITE: "Favourite",
  FORGOT_PASSWORD: "ForgotPassword",
  LOGIN: "Login",
  NOTIFICATION: "Notification",
  MY_WALLET: "MyWallet",
  ON_BOARDING: "OnBoarding",
  OTP: "Otp",
  REGISTER: "Register",
  SETTINGS: "Settings",
  WELCOME: "Welcome",
});
